### ISSUE TITLE
The example code no longer functions at all

### ISSUE THREAD

**Issue by slangberg** [Slotos/passport-reddit#12]
the example code does not work with the latest express, it relays on a outdated config methodology and uses services  no longer packaged with express.  Can you update the example so it works

**Comment by Slotos** [comment]
I believe #9 would remedy this. I'm currently debating with myself whether I should preserve the old example (it's working with older express after all) or just go for the latest version. In any case, I'll add the newer example in a few days, when I get a bit of time to check its correctness.

**Comment by caranicas** [comment]
Hi there, been dealing with this issue for the last two days, and #9 actually doesn't remedy the issue. Everything seems to work fine locally, however when you try on a live server there is a break on the call back url `/auth/reddit/callback?state=mu08UcXW8Atf3K3VSjgHKhJj&code=xsXN3t8o5sNhdP-uKOqq86MDGzY
`
 
I am running on an free tier of an AWS ubuntu server, and this is the error I get. 

```
TokenError
   at Strategy.OAuth2Strategy.parseErrorResponse (/home/ubuntu/login/node_modules/passport-oauth2/lib/strategy.js:320:12)
   at Strategy.OAuth2Strategy._createOAuthError (/home/ubuntu/login/node_modules/passport-oauth2/lib/strategy.js:367:16)
   at /home/ubuntu/login/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /home/ubuntu/login/node_modules/passport-reddit/lib/passport-reddit/strategy.js:92:26
   at passBackControl (/home/ubuntu/login/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/ubuntu/login/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:85:20)
   at IncomingMessage.emit (events.js:179:7)
   at endReadableNT (_stream_readable.js:913:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

I was getting this same error using the previous flow (setting the state using crypto in the auth request) as well. I was hoping this new flow would solve the issue, but it doesn't seem to.  I'm not sure if it is an issue with Express 4 or if it is because I am only running on an http server and not https.

**Comment by Slotos** [comment]
Example was updated with recent rework to ES6 module.
